In [5]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import time

# Preprocesamiento de datos del dataset (dataset preprocessing)

¿cual es la finalidad del preprocesamiento de los datos?
 - limpiar los datos
 - transformar los datos
 - normalizar los datos
 - estandarizar los datos
 - reducir la dimensionalidad de los datos

In [6]:
dataset = pd.read_csv('../data/data.csv')
targets = dataset['diagnosis']
targets.value_counts()

# B = 357
# M = 212  

diagnosis
B    357
M    212
Name: count, dtype: int64

# Normalización de los valores objetivos (targets)

¿porque normalizamos los valores objetivos?
 - para que los valores objetivos tengan la misma escala
 - para que los valores objetivos sean más fáciles de comparar
 - para que los valores objetivos sean más fáciles de visualizar

In [7]:
# para normalizar los datos necesitamos numeros, pero los valores objetivos son strings
# Cambiamos los valores objetivos de string a numeros
targets = targets.map({'M':1, 'B':0})
# ¿que hace el metodo map?
# - mapea los valores de una serie a otros valores
# - en este caso, mapea 'M' a 1 y 'B' a 0
# targets = np.where(targets == 'M', 1, 0) # asi tambien funciona
# revisamos los targets
print('targets:\n', targets.head(20), '\n')  

targets:
 0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    0
Name: diagnosis, dtype: int64 



In [8]:
print('Dataset head:\n', dataset.head(), '\n') #33 columnas
lista = ['Unnamed: 32', 'id', 'diagnosis']
data = dataset.drop(lista, axis = 1 )
# ¿porque eliminamos las columnas Unnamed: 32, id y diagnosis?
# - porque no aportan información relevante
# revisamos los datos
print('data:\n', data.head(20), '\n') #30 columnas
print('data shape:\n', data.shape, '\n')

Dataset head:
          id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_wo

# normalizacion de los datos (features)

¿que es la normalización de los datos?
 - es el proceso de escalar los datos a un rango fijo
 - el rango fijo es generalmente de 0 a 1
 - la normalización de los datos es importante para que los datos tengan la misma escala
 - significa que la desviación estándar de los datos es 1
 - la media de los datos es 0
 - los datos normalizados son más fáciles de comparar

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
scaler = MinMaxScaler()

In [11]:
data = scaler.fit_transform(data)
# ¿que hace el metodo fit_transform?
# - ajusta el escalador a los datos y transforma los datos

In [12]:
# revisamos los datos
print('data normalizado:\n', data, '\n')
# ¿que observamos con el metodo head?
# - que los datos estan normalizados
# - que los datos tienen la misma escala
# - que los datos son más fáciles de comparar
# - que los datos son más fáciles de visualizar

data normalizado:
 [[0.52103744 0.0226581  0.54598853 ... 0.91202749 0.59846245 0.41886396]
 [0.64314449 0.27257355 0.61578329 ... 0.63917526 0.23358959 0.22287813]
 [0.60149557 0.3902604  0.59574321 ... 0.83505155 0.40370589 0.21343303]
 ...
 [0.45525108 0.62123774 0.44578813 ... 0.48728522 0.12872068 0.1519087 ]
 [0.64456434 0.66351031 0.66553797 ... 0.91065292 0.49714173 0.45231536]
 [0.03686876 0.50152181 0.02853984 ... 0.         0.25744136 0.10068215]] 



In [13]:
# separar los datos en datos de entrenamiento y datos de prueba
# ¿porque separamos los datos en datos de entrenamiento y datos de prueba?
# - para entrenar el modelo con los datos de entrenamiento
# - para probar el modelo con los datos de prueba

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, targets, test_size=0.1, random_state=42)
# ¿que hace el metodo train_test_split?
# - divide los datos en datos de entrenamiento y datos de prueba
# - el tamaño de los datos de prueba es 20%
# - el tamaño de los datos de entrenamiento es 80%
# - el estado aleatorio es 42
# ¿que significa el estado aleatorio?
# - significa que los datos se dividen de la misma manera cada vez que se ejecuta el código

In [14]:
# revisamos los datos
print('X_train:\n', X_train, '\n')
print('X_test:\n', X_test, '\n')
print('y_train:\n', y_train, '\n')
print('y_test:\n', y_test, '\n')
print('X_test shape:', X_test.shape, '\n')
print('X_train shape:', X_train.shape, '\n')
print('y_test shape:', y_test.shape, '\n')
print('y_train shape:', y_train.shape, '\n')

X_train:
 [[0.86322117 0.51403449 0.88252367 ... 0.98522337 0.15572639 0.32834842]
 [0.30758673 0.37571863 0.30827172 ... 0.77594502 0.24482555 0.34146661]
 [0.20393772 0.11261414 0.19653099 ... 0.30068729 0.23023852 0.16515807]
 ...
 [0.34592267 0.2404464  0.32140142 ... 0.11453608 0.17602996 0.04040404]
 [0.33125089 0.33513696 0.32706793 ... 0.62783505 0.31815494 0.33097206]
 [0.24605992 0.36557322 0.23101375 ... 0.25536082 0.22255076 0.090122  ]] 

X_test:
 [[0.25978513 0.30064254 0.25775689 ... 0.34879725 0.2856298  0.2129083 ]
 [0.56599934 0.39228948 0.55151683 ... 0.61477663 0.19436231 0.07116621]
 [0.4012968  0.33040243 0.40017967 ... 0.52027491 0.25073921 0.1649613 ]
 ...
 [0.23280799 0.16706121 0.23716398 ... 0.20762887 0.22905579 0.31850977]
 [0.29291495 0.28779168 0.27980098 ... 0.35910653 0.13207175 0.09320478]
 [0.15471627 0.21880284 0.15707277 ... 0.33484536 0.20559827 0.27535091]] 

y_train:
 82     1
39     1
271    0
79     0
2      1
      ..
71     0
106    0
270    